module.exports = {
    tasks: [{
        url: 'https://www.188bet.co.uk/en-gb',
        harFolder: 'dist',
        jobInterval: 15,
        enable: true
    }, {
        url: 'https://www.188bet.co.uk/en-gb/sports',
        harFolder: 'dist',
        jobInterval: 60,
        enable: true
    }, {
        url: 'https://m.188bet.co.uk/en-gb',
        harFolder: 'dist',
        jobInterval: 15,
        enable: true
    }, {
        url: 'https://www.ez-188uk.com/en-gb',
        harFolder: 'dist',
        jobInterval: 15,
        enable: true
    }, {
        url: 'https://www.ez-188uk.com/en-gb/sports',
        harFolder: 'dist',
        jobInterval: 60,
        enable: true
    }, {
        url: 'https://m.ez-188uk.com/en-gb',
        harFolder: 'dist',
        jobInterval: 15,
        enable: true
    }, {
        url: 'https://nogtm-www.ez-188uk.com/en-gb',
        harFolder: 'dist',
        jobInterval: 15,
        enable: true
    }, {
        url: 'https://nogtm-www.ez-188uk.com/en-gb/sports',
        harFolder: 'dist',
        jobInterval: 60,
        enable: true
    }, {
        url: 'https://nogtm-m.ez-188uk.com/en-gb',
        harFolder: 'dist',
        jobInterval: 15,
        enable: true
    }]
}